
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateIncidentParameters {
    /**
    * Label: Description, type: textarea
    */
    String description
    /**
    * Label: Status, type: entry
    */
    String status
    /**
    * Label: Urgency, type: entry
    */
    String urgency
    /**
    * Label: Impact, type: entry
    */
    String impact
    /**
    * Label: First Name, type: entry
    */
    String firstName
    /**
    * Label: Last Name, type: entry
    */
    String lastName
    /**
    * Label: Service Type, type: entry
    */
    String service_Type
    /**
    * Label: Reported Source, type: entry
    */
    String reportedSource
    /**
    * Label: Values, type: textarea
    */
    String values
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static CreateIncidentParameters initParameters(StepParameters sp) {
        CreateIncidentParameters parameters = new CreateIncidentParameters()

        def description = sp.getRequiredParameter('Description').value
        parameters.description = description

        def status = sp.getRequiredParameter('Status').value
        parameters.status = status

        def urgency = sp.getRequiredParameter('Urgency').value
        parameters.urgency = urgency

        def impact = sp.getRequiredParameter('Impact').value
        parameters.impact = impact

        def firstName = sp.getRequiredParameter('First Name').value
        parameters.firstName = firstName

        def lastName = sp.getRequiredParameter('Last Name').value
        parameters.lastName = lastName

        def service_Type = sp.getRequiredParameter('Service_Type').value
        parameters.service_Type = service_Type

        def reportedSource = sp.getRequiredParameter('Reported Source').value
        parameters.reportedSource = reportedSource

        def values = sp.getRequiredParameter('Values').value
        parameters.values = values

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: c396274fbccb5e8232f77840a2d35e24 ===
