
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateChangeRequestParameters {
    /**
    * Label: Description, type: textarea
    */
    String description
    /**
    * Label: Status, type: entry
    */
    String status
    /**
    * Label: Urgency, type: entry
    */
    String urgency
    /**
    * Label: Impact, type: entry
    */
    String impact
    /**
    * Label: First Name, type: entry
    */
    String firstName
    /**
    * Label: Last Name, type: entry
    */
    String lastName
    /**
    * Label: Location Company, type: entry
    */
    String locationCompany
    /**
    * Label: Values, type: textarea
    */
    String values
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static CreateChangeRequestParameters initParameters(StepParameters sp) {
        CreateChangeRequestParameters parameters = new CreateChangeRequestParameters()

        def description = sp.getRequiredParameter('Description').value
        parameters.description = description

        def status = sp.getRequiredParameter('Status').value
        parameters.status = status

        def urgency = sp.getRequiredParameter('Urgency').value
        parameters.urgency = urgency

        def impact = sp.getRequiredParameter('Impact').value
        parameters.impact = impact

        def firstName = sp.getRequiredParameter('First Name').value
        parameters.firstName = firstName

        def lastName = sp.getRequiredParameter('Last Name').value
        parameters.lastName = lastName

        def locationCompany = sp.getRequiredParameter('Location Company').value
        parameters.locationCompany = locationCompany

        def values = sp.getRequiredParameter('Values').value
        parameters.values = values  ?: '{}'

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 4200be66f6449112bebc9d9fe04dc432 ===
