
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateEntryParameters {
    /**
    * Label: Form Name, type: entry
    */
    String formName
    /**
    * Label: Values, type: textarea
    */
    String values
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static CreateEntryParameters initParameters(StepParameters sp) {
        CreateEntryParameters parameters = new CreateEntryParameters()

        def formName = sp.getRequiredParameter('Form Name').value
        parameters.formName = formName

        def values = sp.getRequiredParameter('Values').value
        parameters.values = values

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 41f48342691bbbce652d36630b99be0c ===
