
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetChangeRequestParameters {
    /**
    * Label: Entry ID, type: entry
    */
    String entryID
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static GetChangeRequestParameters initParameters(StepParameters sp) {
        GetChangeRequestParameters parameters = new GetChangeRequestParameters()

        def entryID = sp.getRequiredParameter('Entry ID').value
        parameters.entryID = entryID

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 163a3c605d648d8dbb4304d1ebcb0af5 ===
