
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetIncidentParameters {
    /**
    * Label: Entry ID, type: entry
    */
    String entryID
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static GetIncidentParameters initParameters(StepParameters sp) {
        GetIncidentParameters parameters = new GetIncidentParameters()

        def entryID = sp.getRequiredParameter('Entry ID').value
        parameters.entryID = entryID

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: c3ce29e84b1267a36a50fc0c67442c9b ===
