
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetServiceRequestByRequestNumberParameters {
    /**
    * Label: Request Number, type: entry
    */
    String requestNumber
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static GetServiceRequestByRequestNumberParameters initParameters(StepParameters sp) {
        GetServiceRequestByRequestNumberParameters parameters = new GetServiceRequestByRequestNumberParameters()

        def requestNumber = sp.getRequiredParameter('Request Number').value
        parameters.requestNumber = requestNumber

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: f3ecfeffdf2413840bd7287994b6d78f ===
