
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class UpdateIncidentParameters {
    /**
    * Label: Entry ID, type: entry
    */
    String entryID
    /**
    * Label: Description, type: textarea
    */
    String description
    /**
    * Label: Status, type: entry
    */
    String status
    /**
    * Label: Urgency, type: entry
    */
    String urgency
    /**
    * Label: Impact, type: entry
    */
    String impact
    /**
    * Label: First Name, type: entry
    */
    String firstName
    /**
    * Label: Last Name, type: entry
    */
    String lastName
    /**
    * Label: Values, type: textarea
    */
    String values
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static UpdateIncidentParameters initParameters(StepParameters sp) {
        UpdateIncidentParameters parameters = new UpdateIncidentParameters()

        def entryID = sp.getRequiredParameter('Entry ID').value
        parameters.entryID = entryID

        def description = sp.getParameter('Description').value
        parameters.description = description

        def status = sp.getParameter('Status').value
        parameters.status = status

        def urgency = sp.getParameter('Urgency').value
        parameters.urgency = urgency

        def impact = sp.getParameter('Impact').value
        parameters.impact = impact

        def firstName = sp.getParameter('First Name').value
        parameters.firstName = firstName

        def lastName = sp.getParameter('Last Name').value
        parameters.lastName = lastName

        def values = sp.getParameter('Values').value
        parameters.values = values

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: aefa95d310b741299764c5ffd7c793b7 ===
