
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class UpdateEntryParameters {
    /**
    * Label: Form Name, type: entry
    */
    String formName
    /**
    * Label: Entry ID, type: entry
    */
    String entryID
    /**
    * Label: Values, type: textarea
    */
    String values
    /**
    * Label: , type: entry
    */
    String resultPropertyPath

    static UpdateEntryParameters initParameters(StepParameters sp) {
        UpdateEntryParameters parameters = new UpdateEntryParameters()

        def formName = sp.getRequiredParameter('Form Name').value
        parameters.formName = formName

        def entryID = sp.getRequiredParameter('Entry ID').value
        parameters.entryID = entryID

        def values = sp.getRequiredParameter('Values').value
        parameters.values = values

        def resultPropertyPath = sp.getParameter('resultPropertyPath').value
        parameters.resultPropertyPath = resultPropertyPath  ?: '/myJob/entriesList'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: a0a2faf66416a6965818f51b3b74957b ===
