
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class WaitForChangeRequestWindowAndApprovalParameters {
    /**
    * Label: Infrastructure Change Id, type: entry
    */
    String infrastructureChangeId

    static WaitForChangeRequestWindowAndApprovalParameters initParameters(StepParameters sp) {
        WaitForChangeRequestWindowAndApprovalParameters parameters = new WaitForChangeRequestWindowAndApprovalParameters()

        def infrastructureChangeId = sp.getRequiredParameter('Infrastructure Change Id').value
        parameters.infrastructureChangeId = infrastructureChangeId

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 17579f8771f21fc37309e8880677fbac ===
