
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class WaitForChangeRequestWindowAndApprovalParameters {
    /**
    * Label: Infrastructure Change Id, type: entry
    */
    String infrastructureChangeId
    /**
    * Label: Polling Interval, type: entry
    */
    String pollingInterval

    static WaitForChangeRequestWindowAndApprovalParameters initParameters(StepParameters sp) {
        WaitForChangeRequestWindowAndApprovalParameters parameters = new WaitForChangeRequestWindowAndApprovalParameters()

        def infrastructureChangeId = sp.getRequiredParameter('Infrastructure Change Id').value
        parameters.infrastructureChangeId = infrastructureChangeId

        def pollingInterval = sp.getParameter('Polling Interval').value
        parameters.pollingInterval = pollingInterval  ?: '30'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 76b705679676158da78c5278c8a2880c ===
