
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class WaitForChangeRequestWindowAndApprovalParameters {
    /**
    * Label: Entry ID, type: entry
    */
    String entryID

    static WaitForChangeRequestWindowAndApprovalParameters initParameters(StepParameters sp) {
        WaitForChangeRequestWindowAndApprovalParameters parameters = new WaitForChangeRequestWindowAndApprovalParameters()

        def entryID = sp.getRequiredParameter('Entry ID').value
        parameters.entryID = entryID

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 52c59ae56e97008d34118fe907aef86c ===
